# Generated by Django 5.2.9 on 2026-01-23 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('enabled_by_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(db_column='key', on_delete=django.db.models.deletion.CASCADE, to='flags.featureflag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant'], name='flags_tenan_tenant__1aec3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uq_tenant_flag')],
            },
        ),
    ]
