# Generated by Django 5.2.9 on 2026-01-28 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField()),
                ('data_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
