# Generated by Django 5.2.9 on 2026-01-27 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('support', 'Support')], default='friendly', max_length=16)),
                ('branding_json', models.JSONField(blank=True, default=dict)),
                ('lead_capture_enabled', models.BooleanField(default=False)),
                ('citations_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='chatbots_ch_tenant__f89069_idx'), models.Index(fields=['tenant', 'deleted_at'], name='chatbots_ch_tenant__01c30e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'name'), name='uq_chatbot_tenant_name')],
            },
        ),
    ]
