# Generated by Django 5.x on 2026-01-27
import uuid
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("chatbots", "0001_initial"),
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("name", models.CharField(max_length=200, blank=True, default="")),
                ("primary_email", models.EmailField(max_length=254, blank=True, default="")),
                ("phone", models.CharField(max_length=32, blank=True, default="")),
                ("status", models.CharField(max_length=20, default="new")),
                ("email_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(null=True, blank=True)),
                ("meta_json", models.JSONField(default=dict, blank=True)),
                ("created_at", models.DateTimeField(default=timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(default=timezone.now, db_index=True)),
                ("deleted_at", models.DateTimeField(null=True, blank=True, db_index=True)),
                ("chatbot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leads", to="chatbots.chatbot")),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name="leads", to="conversations.conversation")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leads", to="tenants.tenant")),
            ],
            options={"db_table": "leads"},
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant", "created_at"], name="leads_tenant_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant", "chatbot", "created_at"], name="leads_tenant_chatbot_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant", "primary_email"], name="leads_tenant_email_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant", "phone"], name="leads_tenant_phone_idx"),
        ),
    ]
