# Generated by Django 5.2.9 on 2026-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_tenant__34bb46_idx',
            old_name='leads_tenant_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_tenant__156544_idx',
            old_name='leads_tenant_chatbot_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_tenant__3a6f53_idx',
            old_name='leads_tenant_email_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_tenant__2cc43d_idx',
            old_name='leads_tenant_phone_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('qualified', 'Qualified'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
