# Generated by Django 5.2.9 on 2026-01-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_otp_verification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='otp_verific_tenant__cbbaf0_idx',
            old_name='otp_tenant_lead_created_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='otp_verific_tenant__c443dd_idx',
            old_name='otp_tenant_email_expires_idx',
        ),
    ]
