# Generated by Django 5.2.9 on 2026-01-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadevent',
            new_name='lead_events_tenant__efb09a_idx',
            old_name='lead_events_tenant_lead_created_idx',
        ),
        migrations.RenameIndex(
            model_name='leadevent',
            new_name='lead_events_tenant__8f4e96_idx',
            old_name='lead_events_tenant_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='leadnote',
            new_name='lead_notes_tenant__766e55_idx',
            old_name='lead_notes_tenant_lead_created_idx',
        ),
        migrations.RenameIndex(
            model_name='leadnote',
            new_name='lead_notes_tenant__49db48_idx',
            old_name='lead_notes_tenant_lead_deleted_idx',
        ),
    ]
