# Generated by Django 5.2.9 on 2026-01-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_sla_reminders'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadreminder',
            new_name='lead_remind_tenant__7f5b23_idx',
            old_name='lead_rem_tenant_status_sched_idx',
        ),
        migrations.RenameIndex(
            model_name='leadreminder',
            new_name='lead_remind_tenant__8bf88a_idx',
            old_name='lead_rem_tenant_lead_created_idx',
        ),
        migrations.RenameIndex(
            model_name='leadslapolicy',
            new_name='lead_sla_po_tenant__1bb641_idx',
            old_name='lead_sla_tenant_enabled_idx',
        ),
    ]
