# Generated by Django 5.2.9 on 2026-01-28
from django.db import migrations


SQL_RENAME_1 = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'lead_rem_tenant_status_sched_idx'
    ) THEN
        ALTER INDEX lead_rem_tenant_status_sched_idx RENAME TO lead_remind_tenant__7f5b23_idx;
    END IF;
END $$;
"""

SQL_RENAME_2 = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'lead_rem_tenant_lead_created_idx'
    ) THEN
        ALTER INDEX lead_rem_tenant_lead_created_idx RENAME TO lead_remind_tenant__8bf88a_idx;
    END IF;
END $$;
"""

SQL_RENAME_3 = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'i'
          AND c.relname = 'lead_sla_tenant_enabled_idx'
    ) THEN
        ALTER INDEX lead_sla_tenant_enabled_idx RENAME TO lead_sla_po_tenant__1bb641_idx;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0012_rename_lead_rem_tenant_status_sched_idx_lead_remind_tenant__7f5b23_idx_and_more"),
        # ^ IMPORTANT:
        # If your dependency is different, keep the same dependency that your file currently has.
        # Only replace the operations logic.
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(SQL_RENAME_1, reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(SQL_RENAME_2, reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(SQL_RENAME_3, reverse_sql=migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="leadreminder",
                    old_name="lead_rem_tenant_status_sched_idx",
                    new_name="lead_remind_tenant__7f5b23_idx",
                ),
                migrations.RenameIndex(
                    model_name="leadreminder",
                    old_name="lead_rem_tenant_lead_created_idx",
                    new_name="lead_remind_tenant__8bf88a_idx",
                ),
                migrations.RenameIndex(
                    model_name="leadslapolicy",
                    old_name="lead_sla_tenant_enabled_idx",
                    new_name="lead_sla_po_tenant__1bb641_idx",
                ),
            ],
        ),

        # keep the rest of your original operations (field removals, etc.)
        migrations.RemoveField(
            model_name="leadreminder",
            name="last_channel",
        ),
        migrations.RemoveField(
            model_name="leadreminder",
            name="next_attempt_at",
        ),
    ]
