# Generated by Django 5.2.9 on 2026-01-23 10:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File')], max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('input_text', models.TextField(blank=True, default='')),
                ('input_url', models.URLField(blank=True, default='')),
                ('input_file', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='tenants.tenant')),
            ],
            options={
                'db_table': 'knowledge_source',
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='tenants.tenant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='knowledge.knowledgesource')),
            ],
            options={
                'db_table': 'knowledge_ingestion_job',
            },
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['tenant', 'created_at'], name='knowledge_s_tenant__c1feef_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['tenant', 'source_type'], name='knowledge_s_tenant__f0ce91_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'created_at'], name='knowledge_i_tenant__454cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'status'], name='knowledge_i_tenant__8303bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['source', 'created_at'], name='knowledge_i_source__cdac21_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'source', 'idempotency_key'), name='uq_ingestion_idempotency'),
        ),
    ]
