# Generated by Django 5.2.9 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("cleanup", "Cleanup"),
                    ("extract", "Extract"),
                    ("chunk", "Chunk"),
                    ("index", "Index"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
