# Generated by Django 5.x on 2026-01-28
import uuid
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("url", models.URLField(max_length=1000)),
                ("secret", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True, db_index=True)),
                ("events_json", models.JSONField(default=list, blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(max_length=100, db_index=True)),
                ("payload_json", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=20, default="pending", db_index=True)),
                ("attempts", models.IntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(null=True, blank=True, db_index=True)),
                ("last_http_status", models.IntegerField(null=True, blank=True)),
                ("last_error", models.TextField(null=True, blank=True)),
                ("delivered_at", models.DateTimeField(null=True, blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("endpoint", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="deliveries", to="webhooks.webhookendpoint")),
            ],
        ),
    ]
