# Generated by Django 5.x on 2026-01-28
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("user_id", models.UUIDField(db_index=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("webhook_enabled", models.BooleanField(default=True)),
                ("digest_mode", models.CharField(default="off", max_length=10, db_index=True)),
                ("digest_hour", models.PositiveSmallIntegerField(null=True, blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now, db_index=True)),
            ],
            options={"db_table": "notification_preferences"},
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "user_id"),
                name="uniq_notification_pref_tenant_user",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["tenant_id", "user_id"], name="notif_pref_tenant_user_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["tenant_id", "digest_mode"], name="notif_pref_tenant_digest_idx"),
        ),
    ]
