# Generated by Django 5.2.9 on 2026-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_tenant__52fe84_idx',
            old_name='notif_pref_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_tenant__b3a288_idx',
            old_name='notif_pref_tenant_digest_idx',
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='digest_mode',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Daily'), ('weekly', 'Weekly')], db_index=True, default='off', max_length=10),
        ),
    ]
