# Generated by Django 5.2.9 on 2026-01-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='nevt_tu_dg_cr_idx',
            old_name='notif_evt_tu_digest_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationevent',
            new_name='nevt_tt_cr_idx',
            old_name='notif_evt_ttype_created_idx',
        ),
    ]
