# Generated by Django 5.2.9 on 2026-01-28 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_initial'),
        ('chatbots', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apikey',
            name='uq_api_key_hash_per_chatbot',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_tenant__848296_idx',
            old_name='api_keys_ap_tenant__aca5b5_idx',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['tenant', 'chatbot', 'created_at'], name='api_keys_tenant__834dad_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix'], name='api_keys_key_pre_9c2634_idx'),
        ),
        migrations.AlterModelTable(
            name='apikey',
            table='api_keys',
        ),
    ]
